import { useNavigate } from 'react-router-dom';
import Nav from '../components/Nav';
import Hero from '../components/Hero';
import Footer from '../components/Footer';

const TECH_STACK = ['React', 'Django', 'Python', 'Gemini API', 'Google SSO', 'PostgreSQL', 'Redis', 'Docker', 'Tailwind CSS'];

const HomePage = () => {
  const navigate = useNavigate();

  return (
    <>
      <Nav/>
      <Hero/>
      {/* MISSION */}
      <div className="mission">
        <div>
          <div className="section-kicker">Our mission</div>
          <h2 className="section-heading">One hub. Every resource. Zero hunting.</h2>
          <div className="body-copy">
            <p>Code Platoon moves fast, we’re talking drinking from a firehose speeds. You don’t have the time or mental bandwidth to search through the gigantic pile of resources dumped at your feet in the first few days. As former students, we know how much those resources matter and how buried they get. That’s why we made COMPASS. So no future student loses time digging through bookmarks, Slack pins, and browser history to find what they need. Learning to code is hard. Finding the Zoom link shouldn’t be.</p>
          </div>
        </div>
        <div>
          <div className="pull-quote">
            &ldquo;The function of good software is to make the complex appear to be simple&rdquo;
            <cite>&mdash; Grady Booch, Chief Scientist for Software Engineering at IBM Research</cite>
          </div>
        </div>
      </div>

      {/* FEATURES */}
      <div className="features">
        <div className="section-kicker">What COMPASS does</div>
        <h2 className="section-heading">Three tools, one destination</h2>
        <div className="features-grid">
          <div className="feat">
            <div className="feat-num">01</div>
            <div className="feat-title">Centralized curriculum resource access</div>
            <div className="feat-desc"> Tied to your cohort and linked from one place with context on what each cohort covers.</div>
            <span className="feat-badge badge-teal">Curriculum</span>
          </div>
          <div className="feat feat-bl">
            <div className="feat-num">02</div>
            <div className="feat-title">Live Chicago time clock</div>
            <div className="feat-desc">Code Platoon is based in Chicago and uses Chicago time. COMPASS shows a live CDT/CST clock so students in any time zone never miss a session or deadline.</div>
            <span className="feat-badge badge-orange">Live tool</span>
          </div>
          <div className="feat feat-bt"> 
            <div className="feat-num">03</div>
            <div className="feat-title">AI vocabulary widget</div>
            <div className="feat-desc">Paste any curriculum URL and get a list of related vocabulary words &mdash; definitions and context generated by AI and based off the topic you need right now.</div>
            <span className="feat-badge badge-blue">AI-powered</span>
          </div>
          <div className="feat feat-bt"> 
            <div className="feat-num">04</div>
            <div className="feat-title">All-in-one Link Hub</div>
            <div className="feat-desc">Two widgets = Major power. All the links you need, centralized in one hub for easy access.</div>
            <span className="feat-badge badge-yellow">Link Hub</span>
          </div>
        </div>
      </div>

      {/* TECH STACK */}
      <div className="tech-section">
        <div className="col-head">Tech stack</div>
        <div className="tech-wrap">
          {TECH_STACK.map(t => (
            <span key={t} className="tech-pill">{t}</span>
          ))}
        </div>
        <div className="detail-note">Built with the same stack taught in the curriculum &mdash; COMPASS is a living portfolio piece demonstrating everything learned across all four phases.</div>
      </div>

      {/* CTA BAND */}
      <div className="cta-band">
        <div>
          <div className="cta-text-head">Ready to navigate?</div>
          <div className="cta-text-sub">Head back to the hub and find what you need.</div>
        </div>
        <div className="cta-btns">
          <button className="btn-primary" onClick={() => navigate('/auth')}>&#8962; Get Started</button>
        </div>
      </div>

      <Footer/>
      
    </>
  );
};

export default HomePage;
