import { useNavigate } from 'react-router-dom';
import Nav from '../components/Nav';
import Hero from '../components/Hero';
import Footer from '../components/Footer';

const TECH_STACK = ['React', 'Django', 'Python', 'Gemini API', 'Google SSO', 'PostgreSQL', 'Redis', 'Docker', 'Tailwind CSS'];

const HomePage = () => {
  const navigate = useNavigate();

  return (
    <>
      <Nav/>
      <Hero/>
      {/* MISSION */}
      <div className="mission">
        <div>
          <div className="section-kicker">Our mission</div>
          <h2 className="section-heading">One hub. Every resource. Zero hunting.</h2>
          <div className="body-copy">
            <p>Code Platoon students move fast &mdash; learning copous amounts of material in intensive phases in a matter of months. COMPASS exists so that no one loses time digging through bookmarks, Slack archives, or browser history to find what they need.</p>
            <p>Built by students, for students &mdash; this app is itself a portfolio piece demonstrating the full-stack skills taught in the program.</p>
          </div>
        </div>
        <div>
          <div className="pull-quote">
            &ldquo;Navigate with confidence. COMPASS points every student to the resources, tools, and community they need to succeed at Code Platoon &mdash; and beyond.&rdquo;
            <cite>&mdash; COMPASS, student-built resource hub</cite>
          </div>
        </div>
      </div>

      {/* FEATURES */}
      <div className="features">
        <div className="section-kicker">What COMPASS does</div>
        <h2 className="section-heading">Three tools, one destination</h2>
        <div className="features-grid">
          <div className="feat">
            <div className="feat-num">01</div>
            <div className="feat-title">Centralized curriculum resource access</div>
            <div className="feat-desc"> Tied to your cohort and linked from one place with context on what each cohort covers.</div>
            <span className="feat-badge badge-teal">Curriculum</span>
          </div>
          <div className="feat feat-bl">
            <div className="feat-num">02</div>
            <div className="feat-title">Live Chicago time clock</div>
            <div className="feat-desc">Code Platoon runs on Chicago time. COMPASS shows a live CDT/CST clock so students in any time zone never miss a session or deadline.</div>
            <span className="feat-badge badge-orange">Live tool</span>
          </div>
          <div className="feat feat-bt" style={{ gridColumn: '1 / -1' }}>
            <div className="feat-num">03</div>
            <div className="feat-title">AI vocabulary widget</div>
            <div className="feat-desc">Paste any curriculum URL and get a list of related developer vocabulary terms &mdash; definitions and context generated by AI, tailored to that page&apos;s topic.</div>
            <span className="feat-badge badge-blue">AI-powered</span>
          </div>
        </div>
      </div>

      {/* TECH STACK */}
      <div className="tech-section">
        <div className="col-head">Tech stack</div>
        <div className="tech-wrap">
          {TECH_STACK.map(t => (
            <span key={t} className="tech-pill">{t}</span>
          ))}
        </div>
        <div className="detail-note">Built with the same stack taught in the curriculum &mdash; COMPASS is a living portfolio piece demonstrating everything learned across all four phases.</div>
      </div>

      {/* CTA BAND */}
      <div className="cta-band">
        <div>
          <div className="cta-text-head">Ready to navigate?</div>
          <div className="cta-text-sub">Head back to the hub and find what you need.</div>
        </div>
        <div className="cta-btns">
          <button className="btn-primary" onClick={() => navigate('/auth')}>&#8962; Get Started</button>
        </div>
      </div>

      <Footer/>
      
    </>
  );
};

export default HomePage;
